<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\storage\MKW.Core.Storage\MKW.Core.Storage.csproj" />
    <ProjectReference Include="..\..\crypto\MKW.Cryptography\MKW.Cryptography.csproj" />
    <ProjectReference Include="..\..\common\MKW.Common\MKW.Common.csproj" />
  </ItemGroup>

</Project>
