<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MKW.Core.Common\MKW.Core.Common.csproj" />
    <ProjectReference Include="..\MKW.Core.Storage\MKW.Core.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interface\" />
  </ItemGroup>

</Project>
