<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MKW.Core.Storage\MKW.Core.Storage.csproj" />
    <ProjectReference Include="..\MKW.Cryptography\MKW.Cryptography.csproj" />
    <ProjectReference Include="..\MKW.Common\MKW.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net472'" Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

</Project>
