<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\MKW.Cryptography\MKW.Cryptography.csproj" />
  </ItemGroup>

  <Import Project="..\MKW.Cryptography.BouncyCastle.NETFramework\MKW.Cryptography.BouncyCastle.NETFramework.projitems" Label="Shared" />

</Project>
