<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MKW.Core.Common\MKW.Core.Common.csproj" />
    <ProjectReference Include="..\MKW.Core.Cryptography.Loader\MKW.Core.Cryptography.Loader.csproj" />
    <ProjectReference Include="..\MKW.Core.Cryptography\MKW.Core.Cryptography.csproj" />
    <ProjectReference Include="..\MKW.Core.Storage\MKW.Core.Storage.csproj" />
  </ItemGroup>

</Project>
