<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net472</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup>
    <!--<PublishSingleFile>false</PublishSingleFile>-->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\MKW.Core.Storage.JSON\MKW.Core.Storage.JSON.csproj" />
    <ProjectReference Include="..\MKW.Core.Client\MKW.Core.Client.csproj" />
    <ProjectReference Include="..\MKW.GUI.Images\MKW.GUI.Images.csproj" />
  </ItemGroup>

</Project>
