<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsNetFramework Condition="'$(TargetFramework)' == 'net472'">true</IsNetFramework>
  </PropertyGroup>

  <Import Condition="'$(IsNetFramework)' != ''" Project="..\MKW.Core.Common.NETFramework\MKW.Core.Common.NETFramework.projitems" Label="Shared" />

  <ItemGroup>
    <PackageReference Condition="'$(IsNetFramework)' != ''" Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

</Project>
