// Copyright (c) Timofei Zhakov. All Rights Reserved
// Licensed under the Apache License, Version 2.0.

namespace MKW.GUI.Images
{
    public enum ImageMoniker
    {
        None,
        Add,
        AddDatabase,
        AddKey,
        AddUser,
        Admin,
        AsymmetricKey,
        Close,
        CloseAll,
        CloseSolution,
        Database,
        DatabaseFile,
        DataList,
        Delete,
        DeleteDocument,
        DeleteFolder,
        DeleteKey,
        DeleteUser,
        Edit,
        EditDatabase,
        EditDocument,
        EditKey,
        Export,
        FolderClosed,
        FolderOpened,
        Import,
        Key,
        Lock,
        LoginUser,
        NewDocument,
        NewFolder,
        NewKey,
        NewUser,
        Next,
        OpenFile,
        OpenFolder,
        PasswordBox,
        PasswordStrength,
        ReadOnlyDatabase,
        Save,
        SaveAs,
        StatusHelp,
        StatusInformation,
        StatusOK,
        StatusWarning,
        Team,
        Unlock,
        User,
    }
}
