<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>mkw</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.StartsWith('net8'))">
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

    <ItemGroup>
    <ProjectReference Include="..\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\MKW.Core.Storage.JSON\MKW.Core.Storage.JSON.csproj" />
    <ProjectReference Include="..\MKW.Core.Client\MKW.Core.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta7.25380.108" />
  </ItemGroup>
</Project>
