<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\common\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\..\storage\MKW.Core.Storage\MKW.Core.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interface\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net472'" Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

</Project>
