<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MKW.Core.Cryptography.Loader\MKW.Core.Cryptography.Loader.csproj" />
    <ProjectReference Include="..\MKW.Core.Storage.JSON\MKW.Core.Storage.JSON.csproj" />
    <ProjectReference Include="..\MKW.Core.Client\MKW.Core.Client.csproj" />
    <ProjectReference Include="..\MKW.Testing.Common\MKW.Testing.Common.csproj" />
    <ProjectReference Include="..\MKW\MKW.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
