<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\crypto\MKW.Cryptography\MKW.Cryptography.csproj" />
    <ProjectReference Include="..\..\common\MKW.Common\MKW.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\crypto\MKW.Cryptography.BouncyCastle\MKW.Cryptography.BouncyCastle.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net8'))">
    <ProjectReference Include="..\..\crypto\MKW.Cryptography.System\MKW.Cryptography.System.csproj" />
  </ItemGroup>

</Project>
