<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472</TargetFrameworks>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup>
    <!--<PublishSingleFile>false</PublishSingleFile>-->
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\MKW.Core.Client\MKW.Core.Client.csproj" />
    <ProjectReference Include="..\MKW.GUI.Images\MKW.GUI.Images.csproj" />
    <ProjectReference Include="..\MKW.Core.Storage.JSON\MKW.Core.Storage.JSON.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ApplicationIcon>../../assets/icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net472'" Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

</Project>
