<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\MKW.Core.Serialization\MKW.Core.Serialization.csproj" />
    <ProjectReference Include="..\MKW.Core\MKW.Core.csproj" />
    <ProjectReference Include="..\MKW.Cryptography.Loader\MKW.Cryptography.Loader.csproj" />
    <ProjectReference Include="..\MKW.Cryptography\MKW.Cryptography.csproj" />
    <ProjectReference Include="..\MKW.Storage\MKW.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net472'" Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

</Project>
