<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\MKW.Common\MKW.Common.csproj" />
    <ProjectReference Include="..\MKW.Cryptography\MKW.Cryptography.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
  </PropertyGroup>

</Project>
