name: Build, Test, Publish

on:
  push:
    branches: ["*"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest

    env:
      Parameters: >
        /p:Configuration=Release

    steps:
      - uses: actions/checkout@v4
  
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild /t:Restore
          msbuild /p:Platform=x64 /p:Configuration=Release
          msbuild /p:Platform=x86 /p:Configuration=Release
          msbuild /p:Platform=ARM64 /p:Configuration=Release

      - name: Test
        run: dotnet test

      - name: Publish
        run: |
          dotnet publish src/MKW.GUI --no-build --framework net472 /p:Platform=x64 /p:Configuration=Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: .\out\publish
