name: Build, Test, Publish

on:
  push:
    branches: ["*"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest

    env:
      Parameters: >
        /p:Configuration=Release

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build ${{ env.Parameters }}

      - name: Test
        run: dotnet test --no-build ${{ env.Parameters }}

      - name: Publish
        run: |
          dotnet publish --rid win-x64 --framework net8.0 MKW ${{ env.Parameters }}
          dotnet publish --rid win-x64 --framework net8.0-windows MKW ${{ env.Parameters }}
          dotnet publish --rid win-x64 --framework net8.0-windows MKW.GUI ${{ env.Parameters }}
          dotnet publish --no-build --framework net472 MKW ${{ env.Parameters }}
          dotnet publish --no-build --framework net472 MKW.GUI ${{ env.Parameters }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ matrix.runtime }}
          path: .\out\publish
