name: Build and Release package


on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions: write-all

jobs:
  create-release:
    runs-on: windows-latest

    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_id: ${{ steps.create-release.outputs.id }}

  build:
    runs-on: windows-latest
    environment: release

    needs: create-release

    strategy:
      matrix:
        platform:
        - x64

    env:
      Parameters: >
        /p:Configuration=Release
        /p:Platform=${{ matrix.platform }}
      PublishDir: ${{ github.workspace }}\out\Release\${{ matrix.platform }}\publish

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build ${{ env.Parameters }}

      - name: Test
        run: dotnet test --no-build ${{ env.Parameters }}

      - name: Publish
        run: |
          dotnet publish --no-build MKW ${{ env.Parameters }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign Package
        uses: azure/trusted-signing-action@v0.5.1
        with:
          endpoint: https://eus.codesigning.azure.net/
          trusted-signing-account-name: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERTIFICATE_PROFILE_NAME }}
          files: |
            ${{ env.PublishDir }}\mkw.exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          cache-dependencies: false

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ matrix.platform }}
          path: ${{ env.PublishDir }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ${{ env.PublishDir }}\mkw.exe

      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.PublishDir }}\mkw.exe
          asset_name: mkw.exe
          asset_content_type: application/exe
