name: Build and Release package


on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions: write-all

jobs:
  create-release:
    runs-on: windows-latest

    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_id: ${{ steps.create-release.outputs.id }}

  build:
    runs-on: windows-latest
    environment: release

    needs: create-release

    strategy:
      matrix:
        include:
          - Platform: x64

    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild /t:Restore
          msbuild /p:Platform=${{ matrix.Platform }} /p:Configuration=Release

      - name: Test
        run: dotnet test

      - id: dirs
        run: |
          "PackageDir=$((ls out/publish/MKW.Package_*).FullName)" >> $env:GITHUB_OUTPUT
          "PackageFile=$((ls out/publish/MKW.Package_*/*.msix).FullName)" >> $env:GITHUB_OUTPUT
          "PackageName=$((ls out/publish/MKW.Package_*/*.msix).Name)" >> $env:GITHUB_OUTPUT

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign Package
        uses: azure/trusted-signing-action@v0.5.1
        with:
          endpoint: https://eus.codesigning.azure.net/
          trusted-signing-account-name: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERTIFICATE_PROFILE_NAME }}
          files: |
            ${{ steps.dirs.outputs.PackageFile }}
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          cache-dependencies: false

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ${{ steps.dirs.outputs.PackageFile }}

      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ steps.dirs.outputs.PackageFile }}
          asset_name: ${{ steps.dirs.outputs.PackageName }}
          asset_content_type: application/msix

  publish-release:
    needs:
      - create-release
      - build
    runs-on: windows-latest
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create-release.outputs.release_id }}
