name: Update GitHub Wikis

on:
  push:
    branches: ["trunk"]
    paths:
      - .github/workflows/wiki.yml
      - docs/**

permissions:
  contents: write

jobs:
  wiki:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: mkw-trunk

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: mkw-wiki

      - run: |
          Remove-Item mkw-wiki/* -Exclude .git
          Copy-Item -Recurse mkw-trunk/docs/* mkw-wiki
          git -C mkw-wiki add .

      - name: Check status
        id: check_status
        working-directory: mkw-wiki
        run: |
          if (git status --porcelain) {
            Write-Output "Changes were found."
            Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "has_changed=true"
          }

      - if: steps.check_status.outputs.has_changed == 'true'
        run: |
          git -C mkw-wiki config user.name "github-actions[bot]"
          git -C mkw-wiki config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git -C mkw-wiki commit --message "[automatic] update wiki"
          git -C mkw-wiki push
