name: Update GitHub Wikis

on:
  push:
    branches: ["trunk"]

permissions:
  contents: write

jobs:
  wiki:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: mkw-trunk

      - name: checkout wikis
        run: git clone https://github.com/rimdx/MKW.wiki.git mkw-wiki

      - name: setup git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: |
          Remove-Item mkw-wiki/* -Exclude .git
          Copy-Item -Recurse mkw-trunk/docs/* mkw-wiki
          git -C mkw-wiki commit --all --message "[automatic] update wiki"
          git -C mkw-wiki push
